import React, { useState } from 'react';
import {
  X,
  Store,
  Phone,
  ShieldCheck,
  CheckCircle2,
  Sparkles,
  MapPin,
  Clock,
  QrCode,
  ArrowRight,
  User,
  ShoppingBag,
  CreditCard,
  Upload,
  Copy,
  Check,
  FileCheck,
  Gift,
  AlertCircle,
  RefreshCw,
  Lock,
  Eye,
  EyeOff,
  Mail,
  HelpCircle,
  ShieldAlert,
  AlertTriangle,
  Send,
  Building,
  CheckCheck
} from 'lucide-react';
import { Category, District, Shop } from '../types';
import {
  ADMIN_UPI_ID,
  ADMIN_NAME,
  ADMIN_NAME_MR,
  AGENCY_NAME_MR,
  ADMIN_EMAIL,
  ADMIN_PHONE,
  REGISTRATION_ORIGINAL_PRICE,
  REGISTRATION_DISCOUNTED_PRICE,
  getUpiPaymentUrl,
  compressImageFile,
  generateReferralCode
} from '../utils/helpers';
import { QRCodeDisplay } from './QRCodeDisplay';
import { TermsAndConditionsModal } from './TermsAndConditionsModal';
import confetti from 'canvas-confetti';

interface ShopkeeperAuthModalProps {
  onClose: () => void;
  onLoginSuccess: (shop: Shop) => void;
  onRegisterSubmit?: (shop: Shop) => void;
  allShops: Shop[];
  categories: Category[];
  districts: District[];
  isMarathi: boolean;
  onReferralReward?: (referralCode: string) => void;
}

export const ShopkeeperAuthModal: React.FC<ShopkeeperAuthModalProps> = ({
  onClose,
  onLoginSuccess,
  onRegisterSubmit,
  allShops,
  categories,
  districts,
  isMarathi,
  onReferralReward,
}) => {
  const [authMode, setAuthMode] = useState<'login' | 'register'>('login');
  const [step, setStep] = useState<
    'loginForm' | 'forgotPassword' | 'forgotOtp' | 'registerForm' | 'upiPayment' | 'pendingApprovalScreen'
  >('loginForm');

  // Login Form State
  const [loginIdentifier, setLoginIdentifier] = useState('');
  const [loginPassword, setLoginPassword] = useState('');
  const [showLoginPassword, setShowLoginPassword] = useState(false);

  // Forgot Password State
  const [forgotIdentifier, setForgotIdentifier] = useState('');
  const [forgotShopTarget, setForgotShopTarget] = useState<Shop | null>(null);
  const [resetOtpInput, setResetOtpInput] = useState('');
  const [generatedResetOtp, setGeneratedResetOtp] = useState('1234');
  const [newPassword, setNewPassword] = useState('');
  const [confirmNewPassword, setConfirmNewPassword] = useState('');
  const [showNewPassword, setShowNewPassword] = useState(false);

  // Terms Modal State
  const [showTermsModal, setShowTermsModal] = useState(false);
  const [acceptedTerms, setAcceptedTerms] = useState(true);

  // Registration Form State
  const [shopUsername, setShopUsername] = useState('');
  const [shopMarathiName, setShopMarathiName] = useState('');
  const [shopEnglishName, setShopEnglishName] = useState('');
  const [ownerName, setOwnerName] = useState('');
  const [shopCategory, setShopCategory] = useState('kirana');
  const [customCategoryName, setCustomCategoryName] = useState('');
  const [shopMobile, setShopMobile] = useState('');
  const [shopWhatsapp, setShopWhatsapp] = useState('');
  const [shopEmail, setShopEmail] = useState('');
  const [regPassword, setRegPassword] = useState('');
  const [regConfirmPassword, setRegConfirmPassword] = useState('');
  const [showRegPassword, setShowRegPassword] = useState(false);

  // Mobile OTP Verification for Shop Registration
  const [isMobileVerified, setIsMobileVerified] = useState(false);
  const [mobileOtpCode, setMobileOtpCode] = useState<string | null>(null);
  const [enteredMobileOtp, setEnteredMobileOtp] = useState('');
  const [isSendingMobileOtp, setIsSendingMobileOtp] = useState(false);

  // Referral Code
  const [autoGeneratedRefCode, setAutoGeneratedRefCode] = useState(() => generateReferralCode('MH'));
  const [referralCodeInput, setReferralCodeInput] = useState('');

  // Location selection (Dependent Dropdowns)
  const validDistricts = districts.filter((d) => d.id !== 'all');
  const [selectedDistrictId, setSelectedDistrictId] = useState(validDistricts[0]?.id || 'satara');
  const activeDistrict = validDistricts.find((d) => d.id === selectedDistrictId) || validDistricts[0];
  const [selectedTalukaId, setSelectedTalukaId] = useState(activeDistrict?.talukas?.[0]?.id || '');
  const activeTaluka = activeDistrict?.talukas?.find((t) => t.id === selectedTalukaId) || activeDistrict?.talukas?.[0];

  const [villageSelection, setVillageSelection] = useState<string>(activeTaluka?.villages?.[0] || '');
  const [customVillageName, setCustomVillageName] = useState('');
  const [landmark, setLandmark] = useState('');
  const [fullAddress, setFullAddress] = useState('');
  const [openingHours, setOpeningHours] = useState('सकाळी ८:०० ते रात्री ९:००');
  const [productsServices, setProductsServices] = useState('');
  const [shopUpiId, setShopUpiId] = useState('');
  const [gstNumber, setGstNumber] = useState('');

  // Banner / Photo
  const [bannerUrl, setBannerUrl] = useState(
    'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=1200&q=80'
  );
  const [uploadedPhotoSizeKb, setUploadedPhotoSizeKb] = useState<number | null>(null);
  const [isCompressing, setIsCompressing] = useState(false);

  // Payment State
  const [copiedAdminUpi, setCopiedAdminUpi] = useState(false);
  const [utrNumber, setUtrNumber] = useState('');
  const [errorMsg, setErrorMsg] = useState('');
  const [successMsg, setSuccessMsg] = useState('');

  // Registered Shop info for pending screen
  const [registeredPendingShop, setRegisteredPendingShop] = useState<Shop | null>(null);

  // District change -> updates taluka & villages
  const handleDistrictChange = (distId: string) => {
    setSelectedDistrictId(distId);
    const targetDist = validDistricts.find((d) => d.id === distId);
    if (targetDist?.talukas && targetDist.talukas.length > 0) {
      setSelectedTalukaId(targetDist.talukas[0].id);
      if (targetDist.talukas[0].villages && targetDist.talukas[0].villages.length > 0) {
        setVillageSelection(targetDist.talukas[0].villages[0]);
      }
    } else {
      setSelectedTalukaId('');
      setVillageSelection('');
    }
  };

  // Taluka change -> updates village dropdown
  const handleTalukaChange = (talukaId: string) => {
    setSelectedTalukaId(talukaId);
    const targetTaluka = activeDistrict?.talukas?.find((t) => t.id === talukaId);
    if (targetTaluka?.villages && targetTaluka.villages.length > 0) {
      setVillageSelection(targetTaluka.villages[0]);
    } else {
      setVillageSelection('other');
    }
  };

  const handleRegenerateRefCode = () => {
    const prefix = shopMarathiName ? shopMarathiName.slice(0, 3) : activeDistrict.nameEn.slice(0, 3);
    const newCode = generateReferralCode(prefix);
    setAutoGeneratedRefCode(newCode);
  };

  const handlePhotoUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setIsCompressing(true);
    setErrorMsg('');
    try {
      const { dataUrl, sizeKb } = await compressImageFile(file, 500);
      setBannerUrl(dataUrl);
      setUploadedPhotoSizeKb(sizeKb);
    } catch (err: any) {
      setErrorMsg(err?.message || 'फोटो अपलोड करताना त्रुटी आली.');
    } finally {
      setIsCompressing(false);
    }
  };

  // Mobile OTP Generation Handler
  const handleSendMobileOtp = () => {
    setErrorMsg('');
    const cleanMobile = shopMobile.replace(/\D/g, '');
    if (cleanMobile.length < 10) {
      setErrorMsg(isMarathi ? 'कृपया प्रथम वैध १० अंकी मोबाईल नंबर टाका' : 'Please enter valid 10-digit mobile number');
      return;
    }

    setIsSendingMobileOtp(true);
    const code = Math.floor(1000 + Math.random() * 9000).toString();
    setTimeout(() => {
      setMobileOtpCode(code);
      setIsSendingMobileOtp(false);
      setSuccessMsg(
        isMarathi ? `आपला ४ अंकी पडताळणी ओटीपी कोड: ${code}` : `Your OTP code: ${code}`
      );
    }, 400);
  };

  // Verify Mobile OTP
  const handleVerifyMobileOtp = () => {
    setErrorMsg('');
    if (!enteredMobileOtp || enteredMobileOtp.trim() !== mobileOtpCode) {
      setErrorMsg(isMarathi ? 'चुकीचा ओटीपी टाकला आहे! कृपया पुन्हा तपासा.' : 'Invalid OTP code! Please check.');
      return;
    }

    setIsMobileVerified(true);
    setSuccessMsg(isMarathi ? '✓ मोबाईल नंबरची पडताळणी यशस्वी झाली!' : '✓ Mobile verified successfully!');
  };

  // 1. Password-based Login Handler (with Admin Approval Check)
  const handlePasswordLogin = (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMsg('');

    const rawInput = loginIdentifier.trim();
    if (!rawInput) {
      setErrorMsg(isMarathi ? 'कृपया मोबाईल नंबर, ईमेल आयडी किंवा युजरनेम टाका' : 'Please enter mobile, email or username');
      return;
    }

    if (!loginPassword.trim()) {
      setErrorMsg(isMarathi ? 'कृपया पासवर्ड टाका' : 'Please enter login password');
      return;
    }

    const lowerInput = rawInput.toLowerCase();
    const cleanPhone = rawInput.replace(/\D/g, '');

    // Find registered shop by mobile, email, username, or marathiName
    const found = allShops.find((s) => {
      const matchPhone = cleanPhone.length >= 10 && (
        s.mobile.replace(/\D/g, '') === cleanPhone ||
        (s.whatsapp && s.whatsapp.replace(/\D/g, '') === cleanPhone)
      );
      const matchEmail = s.email && s.email.trim().toLowerCase() === lowerInput;
      const matchUsername = s.username && s.username.trim().toLowerCase() === lowerInput;
      const matchName = s.marathiName && s.marathiName.trim().toLowerCase() === lowerInput;
      return matchPhone || matchEmail || matchUsername || matchName;
    });

    if (!found) {
      setErrorMsg(
        isMarathi
          ? 'या माहितीनुसार कोणतेही दुकान सापडले नाही. कृपया अचूक माहिती भरा किंवा नवीन नोंदणी करा.'
          : 'No shop found with this mobile, email, or username. Please check details or register new shop.'
      );
      return;
    }

    if (found.isDisabled) {
      setErrorMsg(
        isMarathi
          ? 'हे दुकान तात्पुरते निष्क्रिय (Disabled) केले आहे. कृपया अ‍ॅडमिनशी संपर्क साधा (९३०७२२०४५४).'
          : 'This shop is currently disabled. Please contact administrator.'
      );
      return;
    }

    // REQUIREMENT 1: Check Admin Approval status
    if (found.approvalStatus === 'pending') {
      setErrorMsg(
        isMarathi
          ? '⏳ आपले दुकान अद्याप मुख्य अ‍ॅडमिनच्या मंजुरीच्या प्रतीक्षेत आहे (Pending Admin Approval). अ‍ॅडमिनने पडताळणी करून मंजूर (Approve) केल्यानंतरच आपण डॅशबोर्डमध्ये लॉगिन करू शकाल. मदतीसाठी संपर्क: ९३०७२२०४५४.'
          : 'Your shop registration is pending admin approval. You will be able to login once the admin approves it.'
      );
      return;
    }

    if (found.approvalStatus === 'rejected') {
      setErrorMsg(
        isMarathi
          ? '❌ आपली नोंदणी अ‍ॅडमिनद्वारे नाकारण्यात आली आहे (Rejected). अधिक माहितीसाठी अ‍ॅडमिनशी संपर्क साधा (९३०७२२०४५४).'
          : 'Your shop registration was rejected by the admin. Please contact support.'
      );
      return;
    }

    // Check Password
    if (found.password) {
      if (found.password === loginPassword.trim()) {
        confetti({ particleCount: 60, spread: 70 });
        onLoginSuccess(found);
      } else {
        setErrorMsg(isMarathi ? 'चुकीचा पासवर्ड टाकला आहे! कृपया पुन्हा प्रयत्न करा.' : 'Incorrect password! Please try again.');
      }
    } else {
      // Legacy shop without password
      confetti({ particleCount: 50, spread: 60 });
      onLoginSuccess(found);
    }
  };

  // 2. Forgot Password Flow
  const handleInitiateForgotPassword = (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMsg('');
    const input = forgotIdentifier.trim();
    if (!input) {
      setErrorMsg(isMarathi ? 'कृपया नोंदणीकृत मोबाईल, ईमेल किंवा युजरनेम टाका' : 'Please enter registered mobile, email or username');
      return;
    }

    const lowerInput = input.toLowerCase();
    const cleanPhone = input.replace(/\D/g, '');
    const found = allShops.find((s) => {
      const matchPhone = cleanPhone.length >= 10 && (
        s.mobile.replace(/\D/g, '') === cleanPhone ||
        (s.whatsapp && s.whatsapp.replace(/\D/g, '') === cleanPhone)
      );
      const matchEmail = s.email && s.email.trim().toLowerCase() === lowerInput;
      const matchUsername = s.username && s.username.trim().toLowerCase() === lowerInput;
      return matchPhone || matchEmail || matchUsername;
    });

    if (!found) {
      setErrorMsg(
        isMarathi
          ? 'दिलेल्या माहितीनुसार कोणतेही नोंदणीकृत दुकान आढळले नाही.'
          : 'No registered shop found with this info.'
      );
      return;
    }

    const generated = Math.floor(1000 + Math.random() * 9000).toString();
    setGeneratedResetOtp(generated);
    setForgotShopTarget(found);
    setStep('forgotOtp');
    setSuccessMsg(
      isMarathi
        ? `पासवर्ड रीसेट कोड पाठवला आहे! (ईमेल: ${found.email || ADMIN_EMAIL})`
        : `Reset code generated for ${found.name}`
    );
  };

  const handleResetPasswordSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMsg('');

    if (resetOtpInput !== generatedResetOtp && resetOtpInput !== '1234') {
      setErrorMsg(isMarathi ? 'चुकीचा पडताळणी कोड टाकला आहे.' : 'Invalid verification code.');
      return;
    }

    if (newPassword.length < 4) {
      setErrorMsg(isMarathi ? 'नवीन पासवर्ड किमान ४ अक्षरांचा असावा' : 'Password must be at least 4 characters');
      return;
    }

    if (newPassword !== confirmNewPassword) {
      setErrorMsg(isMarathi ? 'दोन्ही पासवर्ड जुळत नाहीत' : 'Passwords do not match');
      return;
    }

    if (forgotShopTarget) {
      forgotShopTarget.password = newPassword;
      confetti({ particleCount: 70, spread: 80 });
      onLoginSuccess(forgotShopTarget);
    }
  };

  // 3. Go to Payment from Registration Form (Enforces OTP Verification)
  const handleGoToPayment = (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMsg('');

    const finalVillage = villageSelection === 'other' ? customVillageName.trim() : villageSelection.trim();

    if (!shopMarathiName.trim() || !ownerName.trim() || !finalVillage || !fullAddress.trim()) {
      setErrorMsg(isMarathi ? 'कृपया सर्व आवश्यक (*) माहिती भरा' : 'Please fill all required fields');
      return;
    }

    if (shopCategory === 'other' && !customCategoryName.trim()) {
      setErrorMsg(isMarathi ? 'कृपया आपल्या व्यवसायाचा/कॅटेगरीचा प्रकार टाईप करा' : 'Please enter custom business category');
      return;
    }

    const cleanMobile = shopMobile.replace(/\D/g, '');
    if (cleanMobile.length < 10) {
      setErrorMsg(isMarathi ? 'कृपया वैध १० अंकी मोबाईल नंबर टाका' : 'Please enter valid 10-digit mobile number');
      return;
    }

    // REQUIREMENT 1: Mobile verification is strictly mandatory
    if (!isMobileVerified) {
      setErrorMsg(
        isMarathi
          ? 'कृपया पुढे जाण्यापूर्वी मोबाईल नंबरची OTP द्वारे पडताळणी करा (Verify Mobile Number with OTP).'
          : 'Please verify your mobile number with OTP first.'
      );
      return;
    }

    // Check unique username if provided
    const trimmedUsername = shopUsername.trim().toLowerCase();
    if (trimmedUsername) {
      const existingUser = allShops.find(
        (s) => s.username && s.username.toLowerCase() === trimmedUsername
      );
      if (existingUser) {
        setErrorMsg(isMarathi ? 'हे युजरनेम आधीच वापरले आहे. कृपया दुसरे युजरनेम टाका.' : 'This username is already taken. Choose another.');
        return;
      }
    }

    if (!regPassword.trim() || regPassword.length < 4) {
      setErrorMsg(isMarathi ? 'कृपया किमान ४ अक्षरी सुरक्षित पासवर्ड तयार करा' : 'Please create a password of at least 4 chars');
      return;
    }

    if (regPassword !== regConfirmPassword) {
      setErrorMsg(isMarathi ? 'पासवर्ड आणि कन्फर्म पासवर्ड जुळत नाहीत' : 'Passwords do not match');
      return;
    }

    if (!acceptedTerms) {
      setErrorMsg(
        isMarathi
          ? 'कृपया सावित्री मल्टीसर्विसेसचे नियम व अटी (पैसे नॉन-रिफंडेबल व सायबर धोरण) मान्य करा'
          : 'Please accept Terms & Conditions before proceeding'
      );
      return;
    }

    setStep('upiPayment');
  };

  const handleCopyAdminUpi = () => {
    navigator.clipboard.writeText(ADMIN_UPI_ID);
    setCopiedAdminUpi(true);
    setTimeout(() => setCopiedAdminUpi(false), 2000);
  };

  // 4. Complete Registration & Submit for Admin Approval (Sets status to 'pending')
  const handleCompleteRegistration = () => {
    const selectedCatObj = categories.find((c) => c.id === shopCategory) || categories[1];
    const targetDistrictObj = districts.find((d) => d.id === selectedDistrictId) || districts[1];

    const todayStr = new Date().toISOString().split('T')[0];
    const timeStr = new Date().toLocaleTimeString('mr-IN', { hour: '2-digit', minute: '2-digit' });

    if (referralCodeInput.trim() && onReferralReward) {
      onReferralReward(referralCodeInput.trim().toUpperCase());
    }

    const finalUsername = shopUsername.trim().toLowerCase() || `shop_${cleanMobileDigits(shopMobile).slice(-6)}`;
    const finalVillage = villageSelection === 'other' ? (customVillageName.trim() || 'महाराष्ट्र गाव') : villageSelection;
    const finalCategoryMr = shopCategory === 'other' ? (customCategoryName.trim() || 'इतर व्यवसाय') : selectedCatObj.nameMr;
    const finalCategoryEn = shopCategory === 'other' ? (customCategoryName.trim() || 'Custom Business') : selectedCatObj.nameEn;

    const newShop: Shop = {
      id: `shop-${Date.now()}`,
      name: shopEnglishName || shopMarathiName,
      marathiName: shopMarathiName,
      ownerName: ownerName,
      username: finalUsername,
      password: regPassword,
      email: shopEmail.trim() || undefined,
      category: shopCategory,
      categoryLabelMr: finalCategoryMr,
      categoryLabelEn: finalCategoryEn,
      mobile: shopMobile.replace(/\D/g, ''),
      whatsapp: (shopWhatsapp || shopMobile).replace(/\D/g, ''),
      bannerUrl: bannerUrl,
      photoUrls: [bannerUrl],
      district: targetDistrictObj.nameMr,
      taluka: activeTaluka?.nameMr || undefined,
      villageOrCity: finalVillage,
      landmark: landmark,
      fullAddress: fullAddress,
      openingHours: openingHours,
      isOpenNow: true,
      isVerified: false,
      rating: 5.0,
      totalReviews: 1,
      offers: [
        {
          id: `off-${Date.now()}`,
          title: 'नवीन दुकान स्पेशल ऑफर!',
          description: 'आमच्या दुकानाला भेट देणाऱ्या सर्व ग्राहकांसाठी विशेष सवलत.',
          discountType: 'percentage',
          discountValue: '१०% सूट',
          validTill: '३१ डिसेंबर २०२६',
          badge: 'खास ऑफर',
        },
      ],
      productsServices: productsServices
        ? productsServices.split(',').map((s) => s.trim()).filter(Boolean)
        : selectedCatObj.popularItems,
      upiId: shopUpiId || undefined,
      gstNumber: gstNumber.trim() ? gstNumber.trim().toUpperCase() : undefined,
      referralCode: autoGeneratedRefCode,
      referredBy: referralCodeInput.trim() ? referralCodeInput.trim().toUpperCase() : undefined,
      referralEarnings: 0,
      referralCount: 0,
      // REQUIREMENT 1: Strictly set to 'pending' until Admin grants approval
      approvalStatus: 'pending',
      joinedDate: todayStr,
      freeTrialEndsAt: todayStr,
      isPaid: true,
      isDisabled: false,
      paymentDetails: {
        amount: REGISTRATION_DISCOUNTED_PRICE,
        date: todayStr,
        time: timeStr,
        upiId: ADMIN_UPI_ID,
        utrNumber: utrNumber.trim() || `UPI-REC-${Date.now().toString().slice(-6)}`,
        status: 'completed',
      },
      stats: {
        views: 1,
        whatsappInquiries: 0,
        callInquiries: 0,
        dealClicks: 0,
      },
      salesHistory: [],
    };

    confetti({ particleCount: 90, spread: 80, origin: { y: 0.6 } });

    // Submit to store without direct login
    if (onRegisterSubmit) {
      onRegisterSubmit(newShop);
    }

    setRegisteredPendingShop(newShop);
    setStep('pendingApprovalScreen');
  };

  function cleanMobileDigits(str: string) {
    return str.replace(/\D/g, '');
  }

  const upiPaymentUri = getUpiPaymentUrl(REGISTRATION_DISCOUNTED_PRICE, 'Aapla Gavatil Dukan Registration');

  return (
    <>
      <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/70 backdrop-blur-xs flex items-center justify-center p-3 sm:p-4 animate-fadeIn font-['Noto_Sans_Devanagari',sans-serif]">
        <div className="bg-white w-full max-w-xl rounded-2xl sm:rounded-3xl shadow-2xl overflow-hidden flex flex-col max-h-[92vh] border border-slate-200">
          {/* Top Header */}
          <div className="bg-gradient-to-r from-orange-600 via-amber-600 to-indigo-900 text-white p-4 sm:p-5 relative shadow-md shrink-0">
            <button
              onClick={onClose}
              className="absolute top-4 right-4 p-1.5 rounded-full bg-black/20 hover:bg-black/40 text-white transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>

            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-2xl bg-white/20 backdrop-blur-md flex items-center justify-center text-white border border-white/30 shadow-inner">
                <Store className="w-7 h-7" />
              </div>
              <div>
                <h2 className="text-lg sm:text-xl font-black">
                  {step === 'pendingApprovalScreen'
                    ? (isMarathi ? 'नोंदणी यशस्वी (मंजुरी प्रलंबित)' : 'Registration Submitted')
                    : authMode === 'login'
                    ? (isMarathi ? 'दुकानदार लॉगिन' : 'Shopkeeper Login')
                    : (isMarathi ? 'नवीन दुकान नोंदणी (₹११)' : 'New Shop Registration (₹11)')}
                </h2>
                <p className="text-xs text-amber-100 font-medium">
                  {AGENCY_NAME_MR} | {ADMIN_NAME_MR}
                </p>
              </div>
            </div>

            {/* Auth Mode Tabs (hidden on pending approval screen) */}
            {step !== 'pendingApprovalScreen' && (
              <div className="flex gap-2 mt-3 pt-3 border-t border-white/20">
                <button
                  type="button"
                  onClick={() => {
                    setAuthMode('login');
                    setStep('loginForm');
                    setErrorMsg('');
                  }}
                  className={`flex-1 py-2 px-3 rounded-xl font-black text-xs transition-all cursor-pointer ${
                    authMode === 'login' && step === 'loginForm'
                      ? 'bg-white text-orange-950 shadow-md scale-102'
                      : 'bg-white/10 hover:bg-white/20 text-white'
                  }`}
                >
                  {isMarathi ? '🔑 दुकानदार लॉगिन' : '🔑 Shop Login'}
                </button>
                <button
                  type="button"
                  onClick={() => {
                    setAuthMode('register');
                    setStep('registerForm');
                    setErrorMsg('');
                  }}
                  className={`flex-1 py-2 px-3 rounded-xl font-black text-xs transition-all cursor-pointer ${
                    authMode === 'register' || step === 'registerForm' || step === 'upiPayment'
                      ? 'bg-white text-orange-950 shadow-md scale-102'
                      : 'bg-white/10 hover:bg-white/20 text-white'
                  }`}
                >
                  {isMarathi ? '✨ नवीन नोंदणी (₹११)' : '✨ Register Shop (₹11)'}
                </button>
              </div>
            )}
          </div>

          {/* Modal Body */}
          <div className="p-4 sm:p-6 overflow-y-auto space-y-4">
            {errorMsg && (
              <div className="p-3 rounded-xl bg-rose-50 border border-rose-200 text-rose-700 text-xs font-bold animate-shake flex items-center gap-2">
                <AlertTriangle className="w-4 h-4 text-rose-600 shrink-0" />
                <span>{errorMsg}</span>
              </div>
            )}

            {successMsg && (
              <div className="p-3 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-bold flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                <span>{successMsg}</span>
              </div>
            )}

            {/* TAB 1: Password-based Login Form */}
            {authMode === 'login' && step === 'loginForm' && (
              <form onSubmit={handlePasswordLogin} className="space-y-4">
                <div className="text-center py-1">
                  <div className="inline-flex p-3 rounded-2xl bg-orange-100 text-orange-600 mb-2 shadow-2xs">
                    <Lock className="w-6 h-6" />
                  </div>
                  <h3 className="text-base font-black text-slate-900">
                    {isMarathi ? 'दुकानदार सुरक्षित लॉगिन' : 'Shopkeeper Login'}
                  </h3>
                  <p className="text-xs text-slate-500 mt-0.5">
                    {isMarathi
                      ? 'आपला युजरनेम, मोबाईल नंबर किंवा ईमेल आयडी आणि पासवर्ड टाका'
                      : 'Enter Username / Mobile / Email & Password to login'}
                  </p>
                </div>

                {/* Login Identifier Field */}
                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">
                    {isMarathi ? 'युजरनेम / मोबाईल नंबर / ईमेल आयडी *' : 'Username / Mobile / Email ID *'}
                  </label>
                  <div className="relative">
                    <User className="w-4 h-4 text-slate-400 absolute left-3.5 top-3" />
                    <input
                      type="text"
                      required
                      value={loginIdentifier}
                      onChange={(e) => setLoginIdentifier(e.target.value)}
                      placeholder={isMarathi ? 'उदा. 98XXXXXXXX किंवा savitri_kirana' : 'e.g. 98XXXXXXXX or username or email'}
                      className="w-full pl-10 pr-4 py-2.5 text-sm font-semibold rounded-xl border border-slate-300 focus:ring-2 focus:ring-orange-500/40 text-slate-900"
                    />
                  </div>
                </div>

                <div>
                  <div className="flex items-center justify-between mb-1">
                    <label className="block text-xs font-bold text-slate-700">
                      {isMarathi ? 'लॉगिन पासवर्ड *' : 'Login Password *'}
                    </label>
                    <button
                      type="button"
                      onClick={() => {
                        setForgotIdentifier(loginIdentifier);
                        setStep('forgotPassword');
                        setErrorMsg('');
                      }}
                      className="text-[11px] text-orange-600 hover:text-orange-800 font-bold cursor-pointer"
                    >
                      {isMarathi ? 'पासवर्ड विसरलात? (Forgot Password)' : 'Forgot Password?'}
                    </button>
                  </div>
                  <div className="relative">
                    <Lock className="w-4 h-4 text-slate-400 absolute left-3.5 top-3" />
                    <input
                      type={showLoginPassword ? 'text' : 'password'}
                      required
                      value={loginPassword}
                      onChange={(e) => setLoginPassword(e.target.value)}
                      placeholder="••••••••"
                      className="w-full pl-10 pr-10 py-2.5 text-sm rounded-xl border border-slate-300 focus:ring-2 focus:ring-orange-500/40 text-slate-900 font-mono"
                    />
                    <button
                      type="button"
                      onClick={() => setShowLoginPassword(!showLoginPassword)}
                      className="absolute right-3 top-3 text-slate-400 hover:text-slate-600 cursor-pointer p-0.5"
                    >
                      {showLoginPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                    </button>
                  </div>
                </div>

                <button
                  type="submit"
                  className="w-full py-3 rounded-xl bg-gradient-to-r from-orange-600 to-amber-600 hover:from-orange-700 hover:to-amber-700 text-white font-black text-sm shadow-md shadow-orange-500/20 transition-all cursor-pointer flex items-center justify-center gap-2"
                >
                  <Lock className="w-4 h-4" />
                  <span>{isMarathi ? 'सुरक्षित लॉगिन करा' : 'Login to My Shop'}</span>
                </button>

                <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 text-center space-y-1">
                  <span className="text-xs text-slate-600">
                    {isMarathi ? 'अजून दुकान नोंदवलेले नाही?' : "Don't have a shop registered yet?"}
                  </span>
                  <button
                    type="button"
                    onClick={() => {
                      setAuthMode('register');
                      setStep('registerForm');
                      setShopMobile(loginIdentifier.replace(/\D/g, ''));
                      setErrorMsg('');
                    }}
                    className="block mx-auto text-xs font-black text-orange-600 hover:text-orange-700 cursor-pointer"
                  >
                    {isMarathi ? '→ नवीन दुकान नोंदणी करा (फक्त ₹११)' : '→ Register New Shop (Only ₹11)'}
                  </button>
                </div>
              </form>
            )}

            {/* Forgot Password Flow */}
            {step === 'forgotPassword' && (
              <form onSubmit={handleInitiateForgotPassword} className="space-y-4">
                <div className="text-center py-1">
                  <div className="inline-flex p-3 rounded-2xl bg-amber-100 text-amber-700 mb-2 shadow-2xs">
                    <Mail className="w-6 h-6" />
                  </div>
                  <h3 className="text-base font-black text-slate-900">
                    {isMarathi ? 'पासवर्ड रीसेट करा (ईमेलवर)' : 'Forgot Password Recovery'}
                  </h3>
                  <p className="text-xs text-slate-500 mt-0.5">
                    {isMarathi ? 'आपला नोंदणीकृत मोबाईल नंबर किंवा ईमेल पत्ता टाका' : 'Enter registered mobile or email to get reset code'}
                  </p>
                </div>

                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">
                    {isMarathi ? 'नोंदणीकृत मोबाईल नंबर किंवा ईमेल *' : 'Mobile Number or Email *'}
                  </label>
                  <input
                    type="text"
                    required
                    value={forgotIdentifier}
                    onChange={(e) => setForgotIdentifier(e.target.value)}
                    placeholder="98XXXXXXXX किंवा shop@example.com"
                    className="w-full px-3.5 py-2.5 text-sm rounded-xl border border-slate-300 focus:ring-2 focus:ring-orange-500/40 text-slate-900"
                  />
                </div>

                <button
                  type="submit"
                  className="w-full py-3 rounded-xl bg-amber-600 hover:bg-amber-700 text-white font-black text-sm shadow-md transition-all cursor-pointer flex items-center justify-center gap-2"
                >
                  <Mail className="w-4 h-4" />
                  <span>{isMarathi ? 'ईमेलवर रीसेट कोड पाठवा' : 'Send Reset Code to Email'}</span>
                </button>

                <button
                  type="button"
                  onClick={() => setStep('loginForm')}
                  className="w-full text-xs text-slate-500 hover:text-slate-800 text-center font-bold cursor-pointer"
                >
                  {isMarathi ? '← लॉगिनकडे परत जा' : '← Back to Login'}
                </button>
              </form>
            )}

            {/* Forgot OTP & New Password Form */}
            {step === 'forgotOtp' && forgotShopTarget && (
              <form onSubmit={handleResetPasswordSubmit} className="space-y-4">
                <div className="text-center py-1">
                  <div className="inline-flex p-3 rounded-2xl bg-emerald-100 text-emerald-700 mb-2 shadow-2xs">
                    <ShieldCheck className="w-6 h-6" />
                  </div>
                  <h3 className="text-base font-black text-slate-900">
                    {isMarathi ? 'नवीन पासवर्ड तयार करा' : 'Set New Password'}
                  </h3>
                  <p className="text-xs text-slate-500 mt-0.5">
                    {isMarathi
                      ? `दुकान: ${forgotShopTarget.marathiName || forgotShopTarget.name}`
                      : `Shop: ${forgotShopTarget.name}`}
                  </p>
                  <div className="mt-2 inline-block bg-amber-100 text-slate-900 px-3 py-1 rounded-full text-xs font-black border border-amber-300">
                    {isMarathi ? `ईमेल पडताळणी कोड: ${generatedResetOtp} (किंवा 1234)` : `Test OTP: ${generatedResetOtp}`}
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">
                    {isMarathi ? 'ईमेलवर आलेला ४-अंकी कोड टाका *' : 'Enter 4-Digit Email Code *'}
                  </label>
                  <input
                    type="text"
                    required
                    maxLength={4}
                    value={resetOtpInput}
                    onChange={(e) => setResetOtpInput(e.target.value)}
                    placeholder="1234"
                    className="w-full text-center tracking-[0.5em] text-xl font-black py-2 rounded-xl border border-slate-300 font-mono text-slate-900"
                  />
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">
                      {isMarathi ? 'नवीन पासवर्ड *' : 'New Password *'}
                    </label>
                    <div className="relative">
                      <input
                        type={showNewPassword ? 'text' : 'password'}
                        required
                        value={newPassword}
                        onChange={(e) => setNewPassword(e.target.value)}
                        placeholder="••••••••"
                        className="w-full pl-3 pr-8 py-2 text-xs sm:text-sm rounded-xl border border-slate-300 font-mono"
                      />
                      <button
                        type="button"
                        onClick={() => setShowNewPassword(!showNewPassword)}
                        className="absolute right-2.5 top-2.5 text-slate-400 p-0.5"
                      >
                        {showNewPassword ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                      </button>
                    </div>
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">
                      {isMarathi ? 'पासवर्ड कन्फर्म करा *' : 'Confirm Password *'}
                    </label>
                    <input
                      type="password"
                      required
                      value={confirmNewPassword}
                      onChange={(e) => setConfirmNewPassword(e.target.value)}
                      placeholder="••••••••"
                      className="w-full px-3 py-2 text-xs sm:text-sm rounded-xl border border-slate-300 font-mono"
                    />
                  </div>
                </div>

                <button
                  type="submit"
                  className="w-full py-3 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-black text-sm shadow-md transition-all cursor-pointer flex items-center justify-center gap-2"
                >
                  <CheckCircle2 className="w-4 h-4" />
                  <span>{isMarathi ? 'पासवर्ड बदला व लॉगिन करा' : 'Save Password & Login'}</span>
                </button>
              </form>
            )}

            {/* TAB 2: Shop Registration Form */}
            {authMode === 'register' && step === 'registerForm' && (
              <form onSubmit={handleGoToPayment} className="space-y-4">
                <div className="bg-gradient-to-r from-orange-50 to-amber-50 p-3.5 rounded-xl border border-orange-200 text-xs text-orange-950 font-bold flex items-start gap-2">
                  <Sparkles className="w-4 h-4 text-orange-600 shrink-0 mt-0.5" />
                  <div>
                    <span className="block font-black">
                      {isMarathi ? 'नवीन दुकानदार नोंदणी (फक्त ₹११ शुल्क)' : 'New Shop Registration (Only ₹11)'}
                    </span>
                    <span className="text-[11px] font-normal text-slate-700 mt-0.5 block">
                      {isMarathi
                        ? 'नोंदणी व पेमेंट पूर्ण झाल्यावर आपले दुकान मुख्य अ‍ॅडमिनकडे पडताळणी व मंजुरीसाठी (Approval) पाठवले जाते. मंजुरीनंतर दुकान सार्वजनिक होईल.'
                        : 'After registration, your shop goes for Admin Verification & Approval before appearing live on the Home page.'}
                    </span>
                  </div>
                </div>

                {/* Auto Generated Referral Code */}
                <div className="p-3 bg-gradient-to-r from-emerald-50 to-teal-50 rounded-xl border border-emerald-200 flex items-center justify-between">
                  <div>
                    <span className="text-[10px] font-bold text-emerald-800 uppercase tracking-wider block">
                      {isMarathi ? 'आपला ऑटो-जनरेट रेफरल कोड:' : 'Auto Generated Referral Code:'}
                    </span>
                    <span className="text-sm font-black font-mono text-emerald-950">
                      {autoGeneratedRefCode}
                    </span>
                  </div>
                  <button
                    type="button"
                    onClick={handleRegenerateRefCode}
                    className="flex items-center gap-1 px-2.5 py-1 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold transition-all cursor-pointer shadow-2xs"
                  >
                    <RefreshCw className="w-3 h-3" />
                    <span>{isMarathi ? 'नवीन कोड' : 'Regenerate'}</span>
                  </button>
                </div>

                {/* Referral Code from Agent / Friend */}
                <div className="p-3 bg-purple-50/70 rounded-xl border border-purple-200 space-y-1">
                  <label className="block text-xs font-bold text-purple-950">
                    {isMarathi ? 'एजंट किंवा मित्राचा रेफरल कोड (ऐच्छिक):' : 'Agent Referral Code (Optional):'}
                  </label>
                  <input
                    type="text"
                    value={referralCodeInput}
                    onChange={(e) => setReferralCodeInput(e.target.value.toUpperCase())}
                    placeholder="उदा. AGT-PUN-8491 किंवा REF-SAT-1234"
                    className="w-full px-3 py-2 text-xs sm:text-sm rounded-xl border border-purple-300 font-mono text-purple-950 bg-white"
                  />
                  <p className="text-[10px] text-purple-700">
                    {isMarathi ? '💡 जर आपल्याला गावातील अधिकृत एजंटने जोडले असेल, तर त्यांचा कोड टाका.' : 'Enter agent code if referred by an agent.'}
                  </p>
                </div>

                {/* Shop Name & Owner */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">
                      {isMarathi ? 'दुकानाचे नाव (मराठीमध्ये) *' : 'Shop Name (Marathi) *'}
                    </label>
                    <input
                      type="text"
                      required
                      value={shopMarathiName}
                      onChange={(e) => {
                        setShopMarathiName(e.target.value);
                        if (!shopUsername) {
                          const suggested = e.target.value.toLowerCase().replace(/[^a-z0-9]/g, '_').slice(0, 15);
                          if (suggested) setShopUsername(suggested);
                        }
                      }}
                      placeholder={isMarathi ? 'उदा. सावित्री किराणा स्टोअर्स' : 'e.g. Savitri Kirana'}
                      className="w-full px-3.5 py-2 text-xs sm:text-sm rounded-xl border border-slate-300 focus:ring-2 focus:ring-orange-500/40 text-slate-900"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">
                      {isMarathi ? 'दुकानदाराचे नाव (संचालक) *' : 'Owner Name *'}
                    </label>
                    <input
                      type="text"
                      required
                      value={ownerName}
                      onChange={(e) => setOwnerName(e.target.value)}
                      placeholder={isMarathi ? 'उदा. अविनाश बनसोडे' : 'e.g. Avinash Bansode'}
                      className="w-full px-3.5 py-2 text-xs sm:text-sm rounded-xl border border-slate-300 focus:ring-2 focus:ring-orange-500/40 text-slate-900"
                    />
                  </div>
                </div>

                {/* Username & Credentials Card */}
                <div className="p-3 bg-slate-50 rounded-2xl border border-slate-200 space-y-2">
                  <div className="font-bold text-xs text-slate-800 flex items-center gap-1.5">
                    <User className="w-4 h-4 text-orange-600" />
                    <span>{isMarathi ? 'दुकान लॉगिन युजरनेम (लॉगिन करण्यासाठी) *' : 'Shop Login Username (For Login) *'}</span>
                  </div>

                  <div>
                    <input
                      type="text"
                      required
                      value={shopUsername}
                      onChange={(e) => setShopUsername(e.target.value.toLowerCase().replace(/\s+/g, '_'))}
                      placeholder={isMarathi ? 'उदा. savitri_kirana किंवा bansode_shop' : 'e.g. savitri_kirana'}
                      className="w-full px-3.5 py-2 text-xs sm:text-sm rounded-xl border border-slate-300 focus:ring-2 focus:ring-orange-500/40 text-slate-900 font-mono"
                    />
                    <p className="text-[10px] text-slate-500 mt-1">
                      {isMarathi
                        ? '💡 हे युजरनेम आपण पासवर्डसह लॉगिन करण्यासाठी वापरू शकता.'
                        : '💡 Use this username along with password to log in anytime.'}
                    </p>
                  </div>
                </div>

                {/* Password Creation during Registration */}
                <div className="p-3 bg-indigo-50/70 rounded-2xl border border-indigo-100 space-y-2">
                  <div className="font-bold text-xs text-indigo-950 flex items-center gap-1.5">
                    <Lock className="w-4 h-4 text-indigo-600" />
                    <span>{isMarathi ? 'दुकान लॉगिन पासवर्ड तयार करा (सुरक्षित व गुप्त) *' : 'Create Shop Login Password *'}</span>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    <div>
                      <label className="block text-[11px] font-bold text-slate-700 mb-1">
                        {isMarathi ? 'पासवर्ड (किमान ४ अक्षरे) *' : 'Create Password *'}
                      </label>
                      <div className="relative">
                        <input
                          type={showRegPassword ? 'text' : 'password'}
                          required
                          value={regPassword}
                          onChange={(e) => setRegPassword(e.target.value)}
                          placeholder="••••••••"
                          className="w-full pl-3 pr-8 py-2 text-xs sm:text-sm rounded-xl border border-slate-300 font-mono bg-white text-slate-900"
                        />
                        <button
                          type="button"
                          onClick={() => setShowRegPassword(!showRegPassword)}
                          className="absolute right-2.5 top-2.5 text-slate-400 p-0.5"
                        >
                          {showRegPassword ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                        </button>
                      </div>
                    </div>

                    <div>
                      <label className="block text-[11px] font-bold text-slate-700 mb-1">
                        {isMarathi ? 'पासवर्डची पुष्टी करा *' : 'Confirm Password *'}
                      </label>
                      <input
                        type="password"
                        required
                        value={regConfirmPassword}
                        onChange={(e) => setRegConfirmPassword(e.target.value)}
                        placeholder="••••••••"
                        className="w-full px-3 py-2 text-xs sm:text-sm rounded-xl border border-slate-300 font-mono bg-white text-slate-900"
                      />
                    </div>
                  </div>
                </div>

                {/* REQUIREMENT 1: Mobile Verification with OTP */}
                <div className="p-3 bg-amber-50/80 rounded-2xl border border-amber-200 space-y-2.5">
                  <div className="flex items-center justify-between">
                    <label className="block text-xs font-bold text-slate-800 flex items-center gap-1.5">
                      <Phone className="w-4 h-4 text-orange-600" />
                      <span>{isMarathi ? 'मोबाईल नंबर व पडताळणी (Mobile OTP) *' : 'Mobile & OTP Verification *'}</span>
                    </label>
                    {isMobileVerified ? (
                      <span className="text-[11px] bg-emerald-100 text-emerald-800 font-black px-2 py-0.5 rounded-md border border-emerald-300 flex items-center gap-1">
                        <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                        {isMarathi ? 'पडताळणी पूर्ण (Verified)' : 'Verified'}
                      </span>
                    ) : (
                      <span className="text-[10px] text-amber-800 font-bold bg-amber-200/80 px-2 py-0.5 rounded-md">
                        {isMarathi ? 'OTP पडताळणी आवश्यक' : 'Verification Required'}
                      </span>
                    )}
                  </div>

                  <div className="flex gap-2">
                    <input
                      type="tel"
                      required
                      maxLength={10}
                      disabled={isMobileVerified}
                      value={shopMobile}
                      onChange={(e) => {
                        const val = e.target.value.replace(/\D/g, '');
                        setShopMobile(val);
                        if (!shopWhatsapp) setShopWhatsapp(val);
                        setIsMobileVerified(false);
                        setMobileOtpCode(null);
                      }}
                      placeholder="98XXXXXXXX"
                      className="flex-1 px-3 py-2 text-xs sm:text-sm rounded-xl border border-slate-300 text-slate-900 font-semibold bg-white"
                    />

                    {!isMobileVerified && (
                      <button
                        type="button"
                        onClick={handleSendMobileOtp}
                        disabled={isSendingMobileOtp || shopMobile.replace(/\D/g, '').length < 10}
                        className="px-3 py-2 rounded-xl bg-orange-600 hover:bg-orange-700 disabled:opacity-50 text-white text-xs font-bold transition-all cursor-pointer shrink-0 flex items-center gap-1"
                      >
                        <Send className="w-3.5 h-3.5" />
                        <span>{mobileOtpCode ? (isMarathi ? 'पुन्हा पाठवा' : 'Resend') : (isMarathi ? 'OTP मिळवा' : 'Send OTP')}</span>
                      </button>
                    )}
                  </div>

                  {mobileOtpCode && !isMobileVerified && (
                    <div className="p-3 bg-white rounded-xl border border-amber-300 space-y-2 animate-fadeIn">
                      <div className="flex items-center justify-between text-xs">
                        <span className="font-black text-amber-950">
                          {isMarathi ? 'आपला ४-अंकी पडताळणी कोड:' : '4-Digit OTP Code:'}
                        </span>
                        <span className="font-mono font-black text-amber-900 bg-amber-100 px-2.5 py-0.5 rounded-md border border-amber-300">
                          {mobileOtpCode}
                        </span>
                      </div>

                      <div className="flex gap-2">
                        <input
                          type="text"
                          maxLength={4}
                          value={enteredMobileOtp}
                          onChange={(e) => setEnteredMobileOtp(e.target.value)}
                          placeholder="1234"
                          className="w-28 text-center text-sm font-black font-mono py-1.5 rounded-xl border border-amber-300 bg-amber-50/50"
                        />
                        <button
                          type="button"
                          onClick={handleVerifyMobileOtp}
                          className="flex-1 py-1.5 px-3 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-black text-xs transition-all cursor-pointer flex items-center justify-center gap-1"
                        >
                          <Check className="w-3.5 h-3.5" />
                          <span>{isMarathi ? 'ओटीपी तपासा (Verify)' : 'Verify OTP'}</span>
                        </button>
                      </div>
                    </div>
                  )}

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-1">
                    <div>
                      <label className="block text-[11px] font-bold text-slate-700 mb-0.5">
                        {isMarathi ? 'WhatsApp नंबर *' : 'WhatsApp Number *'}
                      </label>
                      <input
                        type="tel"
                        required
                        maxLength={10}
                        value={shopWhatsapp}
                        onChange={(e) => setShopWhatsapp(e.target.value.replace(/\D/g, ''))}
                        placeholder="98XXXXXXXX"
                        className="w-full px-3 py-1.5 text-xs rounded-xl border border-slate-300 text-slate-900 font-semibold bg-white"
                      />
                    </div>

                    <div>
                      <label className="block text-[11px] font-bold text-slate-700 mb-0.5">
                        {isMarathi ? 'ईमेल (पासवर्ड रीसेटसाठी)' : 'Email (For Reset)'}
                      </label>
                      <input
                        type="email"
                        value={shopEmail}
                        onChange={(e) => setShopEmail(e.target.value)}
                        placeholder="shop@gmail.com"
                        className="w-full px-3 py-1.5 text-xs rounded-xl border border-slate-300 text-slate-900 bg-white"
                      />
                    </div>
                  </div>
                </div>

                {/* REQUIREMENT 2: Category selector with "Other" & Custom Text Field */}
                <div className="p-3 bg-slate-50 rounded-2xl border border-slate-200 space-y-2">
                  <label className="block text-xs font-bold text-slate-800">
                    {isMarathi ? 'दुकानाची कॅटेगरी निवडा *' : 'Select Category *'}
                  </label>
                  <select
                    value={shopCategory}
                    onChange={(e) => setShopCategory(e.target.value)}
                    className="w-full px-3.5 py-2 text-xs sm:text-sm rounded-xl border border-slate-300 bg-white focus:ring-2 focus:ring-orange-500/40 text-slate-900 font-bold"
                  >
                    {categories.filter((c) => c.id !== 'all').map((cat) => (
                      <option key={cat.id} value={cat.id}>
                        {cat.nameMr} ({cat.nameEn})
                      </option>
                    ))}
                  </select>

                  {shopCategory === 'other' && (
                    <div className="space-y-1 pt-1 animate-fadeIn">
                      <label className="block text-[11px] font-bold text-purple-950">
                        {isMarathi ? 'आपल्या व्यवसायाचा / दुकानाचा प्रकार प्रविष्ट करा *' : 'Custom Shop Category Name *'}
                      </label>
                      <input
                        type="text"
                        required
                        value={customCategoryName}
                        onChange={(e) => setCustomCategoryName(e.target.value)}
                        placeholder={isMarathi ? 'उदा. फर्निचर, नर्सरी, डेकोरेशन, फोटोग्राफी...' : 'e.g. Furniture, Nursery, Decor...'}
                        className="w-full px-3.5 py-2 text-xs rounded-xl border border-purple-300 bg-white text-purple-950 font-bold"
                      />
                    </div>
                  )}
                </div>

                {/* REQUIREMENT 2: Location Mapping (Dependent Dropdown District -> Taluka -> Village) */}
                <div className="p-3 bg-slate-50 rounded-2xl border border-slate-200 space-y-3">
                  <div className="font-bold text-xs text-slate-800 flex items-center gap-1.5">
                    <MapPin className="w-4 h-4 text-orange-600" />
                    <span>{isMarathi ? 'दुकानाचे अचूक ठिकाण (जिल्हा, तालुका व गाव):' : 'Location (District, Taluka & Village):'}</span>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    <div>
                      <label className="block text-[11px] font-bold text-slate-600 mb-1">
                        {isMarathi ? '१. जिल्हा निवडा *' : '1. Select District *'}
                      </label>
                      <select
                        value={selectedDistrictId}
                        onChange={(e) => handleDistrictChange(e.target.value)}
                        className="w-full px-3 py-2 text-xs rounded-xl border border-slate-300 bg-white focus:ring-2 focus:ring-orange-500/40 text-slate-900 font-bold"
                      >
                        {validDistricts.map((dist) => (
                          <option key={dist.id} value={dist.id}>
                            {dist.nameMr} ({dist.nameEn})
                          </option>
                        ))}
                      </select>
                    </div>

                    <div>
                      <label className="block text-[11px] font-bold text-slate-600 mb-1">
                        {isMarathi ? '२. तालुका निवडा *' : '2. Select Taluka *'}
                      </label>
                      <select
                        value={selectedTalukaId}
                        onChange={(e) => handleTalukaChange(e.target.value)}
                        className="w-full px-3 py-2 text-xs rounded-xl border border-slate-300 bg-white focus:ring-2 focus:ring-orange-500/40 text-slate-900 font-bold"
                      >
                        {activeDistrict.talukas && activeDistrict.talukas.length > 0 ? (
                          activeDistrict.talukas.map((t) => (
                            <option key={t.id} value={t.id}>
                              {t.nameMr} ({t.nameEn})
                            </option>
                          ))
                        ) : (
                          <option value="">सर्व तालुके</option>
                        )}
                      </select>
                    </div>
                  </div>

                  <div>
                    <label className="block text-[11px] font-bold text-slate-600 mb-1">
                      {isMarathi ? '३. गाव निवडा (गाव यादी) *' : '3. Select Village *'}
                    </label>
                    <select
                      value={villageSelection}
                      onChange={(e) => setVillageSelection(e.target.value)}
                      className="w-full px-3 py-2 text-xs rounded-xl border border-slate-300 bg-white focus:ring-2 focus:ring-orange-500/40 text-slate-900 font-bold"
                    >
                      {activeTaluka?.villages?.map((v, idx) => (
                        <option key={idx} value={v}>
                          {v}
                        </option>
                      ))}
                      <option value="other">{isMarathi ? 'इतर गाव (Other Village)' : 'Other Village'}</option>
                    </select>

                    {villageSelection === 'other' && (
                      <input
                        type="text"
                        required
                        value={customVillageName}
                        onChange={(e) => setCustomVillageName(e.target.value)}
                        placeholder={isMarathi ? 'आपल्या गावाचे / परिसराचे नाव टाईप करा' : 'Type your village name'}
                        className="mt-2 w-full px-3.5 py-2 text-xs rounded-xl border border-slate-300 bg-white text-slate-900"
                      />
                    )}
                  </div>
                </div>

                {/* Full Address & Landmark */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">
                      {isMarathi ? 'जवळची खूण (Landmark)' : 'Landmark'}
                    </label>
                    <input
                      type="text"
                      value={landmark}
                      onChange={(e) => setLandmark(e.target.value)}
                      placeholder={isMarathi ? 'उदा. बस स्थानकासमोर, मुख्य चौक' : 'Near Bus Stand'}
                      className="w-full px-3.5 py-2 text-xs sm:text-sm rounded-xl border border-slate-300 text-slate-900"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">
                      {isMarathi ? 'कामाची वेळ' : 'Opening Hours'}
                    </label>
                    <input
                      type="text"
                      value={openingHours}
                      onChange={(e) => setOpeningHours(e.target.value)}
                      placeholder="सकाळी ८:०० ते रात्री ९:००"
                      className="w-full px-3.5 py-2 text-xs sm:text-sm rounded-xl border border-slate-300 text-slate-900"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">
                    {isMarathi ? 'संपूर्ण पत्ता *' : 'Full Address *'}
                  </label>
                  <input
                    type="text"
                    required
                    value={fullAddress}
                    onChange={(e) => setFullAddress(e.target.value)}
                    placeholder={isMarathi ? 'दुकान क्र., रस्ता, बाजारपेठ, पिनकोड' : 'Shop No., Market road, Pincode'}
                    className="w-full px-3.5 py-2 text-xs sm:text-sm rounded-xl border border-slate-300 text-slate-900"
                  />
                </div>

                {/* Products & Shop UPI */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">
                      {isMarathi ? 'प्रमुख वस्तू/सेवा (कॉमा देऊन लिहा)' : 'Key Products/Services'}
                    </label>
                    <input
                      type="text"
                      value={productsServices}
                      onChange={(e) => setProductsServices(e.target.value)}
                      placeholder={isMarathi ? 'तांदूळ, तेल, मसाले, गूळ' : 'Rice, Oil, Spices'}
                      className="w-full px-3.5 py-2 text-xs sm:text-sm rounded-xl border border-slate-300 text-slate-900"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-slate-700 mb-1">
                      {isMarathi ? 'आपला UPI आयडी (ग्राहकांकडून पेमेंटसाठी)' : 'Your UPI ID (For Customer Payments)'}
                    </label>
                    <input
                      type="text"
                      value={shopUpiId}
                      onChange={(e) => setShopUpiId(e.target.value)}
                      placeholder="mobile@okhdfcbank / mobile@ybl"
                      className="w-full px-3.5 py-2 text-xs sm:text-sm rounded-xl border border-slate-300 font-mono text-slate-900"
                    />
                  </div>
                </div>

                {/* Photo Upload */}
                <div className="p-3 bg-amber-50/70 rounded-xl border border-amber-200 space-y-2">
                  <div className="flex items-center justify-between">
                    <label className="block text-xs font-bold text-slate-900 flex items-center gap-1.5">
                      <Upload className="w-4 h-4 text-orange-600" />
                      <span>{isMarathi ? 'दुकान / बोर्डाचा फोटो अपलोड करा (कमाल ५०० KB)' : 'Upload Shop Photo (Max 500 KB)'}</span>
                    </label>
                    {uploadedPhotoSizeKb !== null && (
                      <span className="text-[10px] bg-emerald-100 text-emerald-800 font-bold px-2 py-0.5 rounded-md border border-emerald-300">
                        {uploadedPhotoSizeKb} KB ✓
                      </span>
                    )}
                  </div>

                  <div className="flex items-center gap-3">
                    <label className="flex-1 cursor-pointer flex items-center justify-center gap-2 px-4 py-2.5 bg-white hover:bg-slate-50 rounded-xl border border-dashed border-orange-400 text-xs font-bold text-orange-700 transition-colors shadow-2xs">
                      <Upload className="w-4 h-4" />
                      <span>{isCompressing ? 'फोटो कंप्रेस होत आहे...' : (isMarathi ? 'गॅलरी किंवा कॅमेऱ्यातून फोटो निवडा' : 'Choose Photo')}</span>
                      <input
                        type="file"
                        accept="image/*"
                        onChange={handlePhotoUpload}
                        disabled={isCompressing}
                        className="hidden"
                      />
                    </label>

                    {bannerUrl && (
                      <div className="w-16 h-12 rounded-xl overflow-hidden border border-slate-300 shrink-0 bg-slate-900">
                        <img src={bannerUrl} alt="Preview" className="w-full h-full object-cover" referrerPolicy="no-referrer" />
                      </div>
                    )}
                  </div>
                </div>

                {/* Terms and Conditions Agreement Checkbox */}
                <div className="p-3.5 bg-slate-50 rounded-2xl border-2 border-orange-300 space-y-2">
                  <div className="flex items-start gap-2.5">
                    <input
                      type="checkbox"
                      id="termsCheckbox"
                      checked={acceptedTerms}
                      onChange={(e) => setAcceptedTerms(e.target.checked)}
                      className="mt-0.5 w-4 h-4 text-orange-600 rounded border-slate-300 focus:ring-orange-500 cursor-pointer"
                    />
                    <label htmlFor="termsCheckbox" className="text-xs text-slate-800 leading-snug cursor-pointer">
                      <span className="font-bold text-slate-900">
                        {isMarathi
                          ? 'मी सावित्री मल्टीसर्विसेसचे नियम व अटी (नोंदणी फी ₹११ नॉन-रिफंडेबल, सायबर अटॅक / तांत्रिक बिघाड धोरण) मान्य करतो/करते.'
                          : 'I agree to the Terms & Conditions (Non-refundable ₹11 registration fee, cyber policy).'}
                      </span>
                    </label>
                  </div>
                  <div className="pl-6 flex items-center justify-between text-[11px]">
                    <span className="text-slate-500">
                      {isMarathi ? 'नोंदणी फी कोणत्याही कारणास्तव परत केली जात नाही.' : 'Fee is strictly non-refundable.'}
                    </span>
                    <button
                      type="button"
                      onClick={() => setShowTermsModal(true)}
                      className="text-orange-600 font-bold hover:underline cursor-pointer"
                    >
                      {isMarathi ? 'नियम व अटी वाचा →' : 'Read Terms →'}
                    </button>
                  </div>
                </div>

                <button
                  type="submit"
                  className="w-full py-3 rounded-xl bg-gradient-to-r from-orange-600 to-amber-600 hover:from-orange-700 hover:to-amber-700 text-white font-black text-sm shadow-md shadow-orange-500/20 transition-all cursor-pointer flex items-center justify-center gap-2"
                >
                  <span>{isMarathi ? 'पुढील पायरी: ₹११ पेमेंट करा' : 'Next: Pay ₹11 via UPI'}</span>
                  <ArrowRight className="w-4 h-4" />
                </button>
              </form>
            )}

            {/* TAB 3: UPI Payment (₹11 to 9307220454@pz) */}
            {step === 'upiPayment' && (
              <div className="space-y-4 animate-fadeIn">
                <div className="text-center py-1">
                  <div className="inline-flex p-3 rounded-2xl bg-orange-100 text-orange-600 mb-2 shadow-2xs">
                    <QrCode className="w-6 h-6" />
                  </div>
                  <h3 className="text-lg font-black text-slate-900">
                    {isMarathi ? 'दुकानदार नोंदणी शुल्क (₹११ UPI पेमेंट)' : 'Pay ₹11 Registration Fee'}
                  </h3>
                  <div className="mt-1 flex items-center justify-center gap-2 text-xs">
                    <span className="line-through text-slate-400 font-bold">
                      {isMarathi ? `मूळ शुल्क: ₹${REGISTRATION_ORIGINAL_PRICE}` : `Original: ₹${REGISTRATION_ORIGINAL_PRICE}`}
                    </span>
                    <span className="bg-emerald-100 text-emerald-800 font-black px-2 py-0.5 rounded-md">
                      ९०% सवलत - फक्त ₹{REGISTRATION_DISCOUNTED_PRICE} (मर्यादित ऑफर)
                    </span>
                  </div>
                </div>

                {/* QR Code & UPI Details Box */}
                <div className="p-5 bg-slate-950 text-white rounded-3xl text-center space-y-4 shadow-xl border border-slate-800">
                  <div className="flex justify-center">
                    <QRCodeDisplay
                      value={upiPaymentUri}
                      size={175}
                      showDownload={true}
                      downloadFileName="aapla-dukan-registration-qr.png"
                      label={isMarathi ? 'GPay / PhonePe / Paytm / BHIM ने स्कॅन करा' : 'Scan via Any UPI App'}
                    />
                  </div>

                  <div className="space-y-1.5 pt-2 border-t border-slate-800">
                    <div className="text-xs text-amber-300 font-bold">
                      {isMarathi ? 'अधिकृत संचालक:' : 'Admin:'} {ADMIN_NAME_MR} ({AGENCY_NAME_MR})
                    </div>
                    <div className="font-mono text-sm font-black text-amber-300 bg-white/10 py-1.5 px-3.5 rounded-xl inline-flex items-center gap-2 border border-white/20">
                      <span>{ADMIN_UPI_ID}</span>
                      <button
                        type="button"
                        onClick={handleCopyAdminUpi}
                        className="p-1 text-amber-300 hover:text-white cursor-pointer bg-white/10 rounded-md"
                        title="UPI ID कॉपी करा"
                      >
                        {copiedAdminUpi ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
                      </button>
                    </div>
                    {copiedAdminUpi && (
                      <span className="text-[11px] text-emerald-400 block font-bold">✓ UPI ID कॉपी झाला!</span>
                    )}
                    <div className="text-base font-black text-white">
                      रक्कम: <span className="text-amber-400">₹{REGISTRATION_DISCOUNTED_PRICE}.००</span> (नॉन-रिफंडेबल)
                    </div>
                  </div>

                  <a
                    href={upiPaymentUri}
                    className="inline-flex items-center justify-center gap-2 px-5 py-3 rounded-xl bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-600 hover:to-teal-600 text-white font-black text-xs sm:text-sm shadow-lg transition-all w-full active:scale-98"
                  >
                    <CreditCard className="w-4 h-4" />
                    <span>{isMarathi ? `थेट UPI ॲप उघडा (Pay ₹${REGISTRATION_DISCOUNTED_PRICE} via UPI)` : `Open UPI App to Pay ₹${REGISTRATION_DISCOUNTED_PRICE}`}</span>
                  </a>
                </div>

                {/* UTR reference */}
                <div className="space-y-1.5">
                  <label className="block text-xs font-bold text-slate-700">
                    {isMarathi ? 'पेमेंट Transaction UTR / संदर्भ नंबर (ऐच्छिक):' : 'Transaction UTR / Ref No (Optional):'}
                  </label>
                  <input
                    type="text"
                    value={utrNumber}
                    onChange={(e) => setUtrNumber(e.target.value)}
                    placeholder="उदा. 4235XXXXXXXX किंवा UPI संदर्भ नंबर"
                    className="w-full px-3.5 py-2 text-xs rounded-xl border border-slate-300 focus:ring-2 focus:ring-orange-500/40 text-slate-900 font-mono"
                  />
                </div>

                {/* Important Pending Approval Notice */}
                <div className="p-3.5 bg-amber-500/10 border border-amber-400/80 rounded-2xl flex items-start gap-2.5 text-xs text-amber-950">
                  <Clock className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
                  <div>
                    <span className="font-black block text-amber-900">
                      {isMarathi ? '⏳ नोंदणी प्रक्रियेची महत्त्वाची माहिती (Pending Status):' : 'Important Note on Shop Approval:'}
                    </span>
                    <p className="text-[11px] leading-relaxed text-amber-800 mt-0.5">
                      {isMarathi
                        ? 'नोंदणी पूर्ण झाल्यानंतर आपले दुकान "मंजुरी प्रलंबित" (Pending Approval) स्थितीत राहील. मुख्य अ‍ॅडमिनने पडताळणी करून मंजूर (Approve) केल्यानंतरच आपले दुकान सार्वजनिक होमपेजवर दिसेल व आपण लॉगिन करू शकाल.'
                        : 'New registrations are placed in "Pending Approval" status and will appear on the public directory after verification by the admin.'}
                    </p>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={handleCompleteRegistration}
                  className="w-full py-3.5 rounded-xl bg-gradient-to-r from-orange-600 to-amber-600 hover:from-orange-700 hover:to-amber-700 text-white font-black text-sm shadow-md shadow-orange-500/20 transition-all cursor-pointer flex items-center justify-center gap-2"
                >
                  <CheckCircle2 className="w-5 h-5" />
                  <span>{isMarathi ? 'पेमेंट पूर्ण झाले, नोंदणी दाखल करा!' : 'Payment Done, Submit Registration!'}</span>
                </button>

                <button
                  type="button"
                  onClick={() => setStep('registerForm')}
                  className="w-full text-xs text-slate-500 hover:text-slate-800 text-center font-bold cursor-pointer py-1"
                >
                  {isMarathi ? '← फॉर्ममध्ये बदल करा' : '← Edit Form Details'}
                </button>
              </div>
            )}

            {/* TAB 4: Registration Submitted & Pending Approval Success Screen */}
            {step === 'pendingApprovalScreen' && registeredPendingShop && (
              <div className="space-y-5 animate-fadeIn text-center py-2">
                <div className="w-16 h-16 rounded-3xl bg-amber-100 text-amber-700 flex items-center justify-center mx-auto shadow-md border border-amber-300">
                  <Clock className="w-9 h-9" />
                </div>

                <div className="space-y-1">
                  <span className="text-xs bg-amber-200/80 text-amber-950 font-black px-3 py-1 rounded-full uppercase tracking-wider">
                    {isMarathi ? 'मंजुरी प्रलंबित (Pending Admin Approval)' : 'Pending Approval'}
                  </span>
                  <h3 className="text-xl font-black text-slate-900 pt-1">
                    {isMarathi ? 'नोंदणी यशस्वीरीत्या दाखल झाली!' : 'Registration Submitted Successfully!'}
                  </h3>
                  <p className="text-xs text-slate-600 max-w-md mx-auto">
                    {isMarathi
                      ? `आपल्या "${registeredPendingShop.marathiName}" दुकानाची नोंदणी व पेमेंट मुख्य अ‍ॅडमिनकडे तपासणीसाठी पाठवले आहे.`
                      : 'Your shop registration has been sent to the Platform Admin for approval.'}
                  </p>
                </div>

                {/* Summary Card */}
                <div className="bg-slate-50 rounded-2xl p-4 border border-slate-200 text-left space-y-2 text-xs">
                  <div className="font-bold text-slate-900 flex justify-between">
                    <span>दुकान नाव:</span>
                    <span className="font-black text-orange-950">{registeredPendingShop.marathiName}</span>
                  </div>
                  <div className="text-slate-600 flex justify-between">
                    <span>दुकानदार / मालक:</span>
                    <span className="font-semibold text-slate-900">{registeredPendingShop.ownerName}</span>
                  </div>
                  <div className="text-slate-600 flex justify-between">
                    <span>मोबाईल नंबर:</span>
                    <span className="font-semibold text-slate-900">+91 {registeredPendingShop.mobile}</span>
                  </div>
                  <div className="text-slate-600 flex justify-between">
                    <span>युजरनेम (Login):</span>
                    <span className="font-mono font-bold text-indigo-900">{registeredPendingShop.username}</span>
                  </div>
                  <div className="text-slate-600 flex justify-between">
                    <span>गाव व जिल्हा:</span>
                    <span className="font-semibold text-slate-900">{registeredPendingShop.villageOrCity}, {registeredPendingShop.district}</span>
                  </div>
                  <div className="text-slate-600 flex justify-between">
                    <span>नोंदणी शुल्क:</span>
                    <span className="font-bold text-emerald-700">₹११.०० (Paid ✓)</span>
                  </div>
                </div>

                {/* Explanatory Notice */}
                <div className="p-3.5 bg-blue-50/80 rounded-2xl border border-blue-200 text-left text-xs text-blue-950 space-y-1">
                  <div className="font-black flex items-center gap-1.5">
                    <ShieldCheck className="w-4 h-4 text-blue-600" />
                    <span>{isMarathi ? 'पुढील पायरी काय असेल?' : 'What happens next?'}</span>
                  </div>
                  <p className="text-[11px] leading-relaxed text-blue-900">
                    {isMarathi
                      ? '१. मुख्य अ‍ॅडमिन (अविनाश बनसोडे) आपल्या दुकानाची माहिती व पेमेंट पडताळणी करतील.\n२. अ‍ॅडमिनने मंजुरी (Approve) दिल्यावर आपले दुकान गावकऱ्यांच्या शोध परिणामांत दिसेल.\n३. मंजुरीनंतरच आपण आपल्या युजरनेम व पासवर्डने डॅशबोर्डमध्ये लॉगिन करू शकाल.'
                      : '1. Admin will verify details and approve.\n2. Once approved, shop goes live and you can login.'}
                  </p>
                </div>

                <div className="flex flex-col sm:flex-row gap-3 pt-2">
                  <button
                    type="button"
                    onClick={onClose}
                    className="flex-1 py-3 rounded-xl bg-slate-900 hover:bg-slate-800 text-white font-black text-xs transition-colors cursor-pointer"
                  >
                    {isMarathi ? 'समजले, मुख्य पृष्ठावर जा' : 'Close & Go to Home'}
                  </button>

                  <button
                    type="button"
                    onClick={() => {
                      setAuthMode('login');
                      setStep('loginForm');
                      setLoginIdentifier(registeredPendingShop.username || registeredPendingShop.mobile);
                      setErrorMsg('');
                    }}
                    className="flex-1 py-3 rounded-xl bg-gradient-to-r from-orange-600 to-amber-600 hover:from-orange-700 hover:to-amber-700 text-white font-black text-xs shadow-md transition-all cursor-pointer"
                  >
                    {isMarathi ? 'लॉगिन पेजवर जा' : 'Go to Login Page'}
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Terms & Conditions Modal */}
      <TermsAndConditionsModal
        isOpen={showTermsModal}
        onClose={() => setShowTermsModal(false)}
        isMarathi={isMarathi}
      />
    </>
  );
};
